Retropikzel gambit (#167)
* Update Gambit workflow
* Update Kawa wokflow

diff --git a/implementations/gambit/head/Dockerfile.alpine b/implementations/gambit/head/Dockerfile.alpine
--- a/implementations/gambit/head/Dockerfile.alpine
+++ b/implementations/gambit/head/Dockerfile.alpine
@@ -1,11 +1,9 @@
 # -*- mode: dockerfile; coding: utf-8 -*-
-
-# NOTE: A shallow clone (git clone --depth 1) causes an obscure build
-# failure for unknown reasons. That's why we use a full clone.
-
 FROM alpine AS build
 RUN apk add gcc make ghostscript texinfo git musl-dev
 WORKDIR /build
+# NOTE: A shallow clone (git clone --depth 1) causes an obscure build
+# failure for unknown reasons. That's why we use a full clone.
 RUN git clone https://github.com/gambit/gambit.git
 WORKDIR /build/gambit
 RUN ./configure --prefix=/usr/local \
@@ -13,12 +11,12 @@ RUN ./configure --prefix=/usr/local \
       --enable-targets=js \
       --enable-default-compile-options="(compactness 9)"
 RUN ln -s /usr/local/bin/gsc gsc-boot
-RUN make || (rm -rf boot/ gsc-boot && make)
-RUN make modules
+RUN make -j$(nproc) || (rm -rf boot/ gsc-boot && make)
+RUN make -j$(nproc) modules
 RUN make check
 RUN make install
 
-FROM alpine debian:trixie-slim
+FROM alpine
 RUN apk add gcc musl-dev mbedtls
 COPY --from=build /usr/local/ /usr/local/
 CMD ["scheme-banner"]
